// src/routes/Error.tsx
import { useSearchParams } from "react-router";

function Error() {
    const [params] = useSearchParams();
    const status = params.get("status") ?? 500;

    return (
        <>
            <div className="absolute left-0 right-0 top-(--header-height) bottom-0 flex items-center justify-center">
                <div>
                    <h1>Error &#123; {status} &#125;</h1>
                    <p>
                        Sorry, we encountered an error, please try again later
                        or reach out for support with the above error code.
                    </p>
                </div>
            </div>
        </>
    );
}

export default Error;

// src/routes/error/+page.svelte
<script lang="ts">
    import { page } from "$app/state";
    import Button from "$lib/components/Button.svelte";

    let status = page.url.searchParams.get("status") || "500";
</script>

<div>
    <div
        class="text-4xl absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
    >
        <h1>
            error code <em>{status}</em>.
        </h1>
        <p>
            Please reach out for support with the error code, or try again
            later.
        </p>
        <Button
            onclick={() => {
                history.back();
            }}
            label="Go back"
            icon="keyboard_backspace"
        />
    </div>
</div>
