// src/lib/components/Form/Errors.svelte
<script lang="ts">
    import type { Error } from "$lib/types";
    import { teleport } from "$lib/util";

    export let errors:Array<Error> = [];
</script>

{#if errors.length > 0}
    {#each errors as error (error.field)}
        <p use:teleport="{{id:error.field}}" class="text-red-400 text-sm">{error.message}</p>
    {/each}
{/if}

// src/components/Errors.tsx
import { createPortal } from "react-dom";
import type { TypeError } from "../services/api_service/types";

type TypeProps = {
    errors: TypeError[];
    shouldUsePortal: boolean;
};

function Errors({ errors, shouldUsePortal }: TypeProps) {
    if (errors.length > 0) {
        return (
            <>
                {errors.map((v, _) => {
                    const portalElem = document.getElementById(
                        `field.${v.field}`,
                    );
                    const elem = (
                        <p className="text-red-400 text-sm animate-slide-in">
                            {v.message}
                        </p>
                    );

                    return shouldUsePortal && portalElem != null
                        ? createPortal(elem, portalElem)
                        : elem;
                })}
            </>
        );
    }
}

export default Errors;
