// src/lib/components/Modal.svelte

<script>
    import { fade, slide } from 'svelte/transition';
    import Button from './Button.svelte';
    let open = false;

    export const toggle = () => {open = !open};
    export const close = () => {open = false};
</script>


{#if open}
    <div class="modal-component">
        <div transition:fade
            on:click|self={close}
            on:keydown={close}
            role="button"
            tabindex="-1"
            class="modal-component outer" >
            <!--empty div to simulate containing div with opacity that does not affect child elements opacity-->
        </div>
        <div transition:slide class="inner">
            <div class="close-button">
                <Button icon="close" onclick={toggle} />
            </div>
            <slot></slot>
        </div>
    </div>
{/if}

<style>
    .modal-component {
        z-index: 10000;
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .outer {
        z-index: unset;
        background-color: #303030;
        opacity: 0.5;
    }
    .inner {
        z-index: 1;
        display: inline-block;
        height: fit-content;
        margin-left: auto;
        margin-right: auto;
        background-color: var(--color-back-2);
        border-radius: 5px;
        padding: 20px;
        border-top: var(--color-back-3) solid 10px;
        border-bottom: var(--color-back-3) solid 10px;
        opacity: 1;
    }
    .close-button {
        position: relative;
        float: right;
        right: 0px;
        top: 0px;
    }
</style>

// src/components/Modal.tsx
import { useCallback, useEffect, useState, type ReactNode } from "react";
import Button from "./Button";
import Icon from "./Icon";

export type TypeProps = {
    isOpen: boolean;
    close: () => void;
    children: ReactNode;
};

export type TypeUseModal = {
    isOpen: boolean;
    open: () => void;
    close: () => void;
    toggle: () => void;
};

export function useStateModal(initialState = false): TypeUseModal {
    const [isOpen, setIsOpen] = useState(initialState);

    const open = useCallback(() => setIsOpen(true), []);
    const close = useCallback(() => setIsOpen(false), []);
    const toggle = useCallback(() => setIsOpen((prev) => !prev), []);

    return { isOpen, open, close, toggle };
}

function Modal({ children, isOpen, close }: TypeProps) {
    const [shouldRender, setShouldRender] = useState(isOpen);

    useEffect(() => {
        if (isOpen) {
            setShouldRender(true);
        }
    }, [isOpen]);

    function handleAnimationEnd() {
        if (!isOpen) {
            setShouldRender(false);
        }
    }

    if (!shouldRender) {
        return null;
    }

    return (
        <>
            <div
                className={`z-50 absolute inset-0 flex justify-center items-center `}
                onAnimationEnd={handleAnimationEnd}
            >
                <div
                    onClick={close}
                    className={`${isOpen ? "animate-fade-in" : "animate-fade-out"}`}
                >
                    {/* Empty so that opacity does not affect "inner" */}
                    <div className="bg-[#303030] opacity-50 z-unset absolute inset-0 "></div>
                </div>
                <div
                    className={`z-10 rounded-md border-t-8 border-b-8 border-back-3 p-4 opacity-100 h-fit w-full sm:w-fit sm:min-w-md bg-back-2 ${isOpen ? "animate-slide-in" : "animate-slide-out"}`}
                >
                    <span className="ml-1 float-right">
                        <Button onClick={close}>
                            <Icon iconName="close"></Icon>
                        </Button>
                    </span>
                    {children}
                </div>
            </div>
        </>
    );
}

export default Modal;
